Use XDG Base Directory Specification for logs and settings
SolarLune/masterplan pull request #40
Opened 2020-11-18 18:11 UTC by theogen-ratkin

Currently, the program writes log and setting files to the same directory where the binary is, which is generally considered a bad practice, because binaries are usually installed to system directories (such as `C:\Program Files` or `/usr/bin`), and users would need administrator privileges write to those files. Even if this is circumvented somehow, all users would share same settings file, which is not good either.

[XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines common environment variables for programs to adhere, that users can set however they wish, and if not set, fallback to reasonable system defaults.

This branch makes use of [adrg/xdg](https://github.com/adrg/xdg) Go package and sets the following default paths for log and settings file:

For `log.txt`:
- `XDG_DATA_HOME/MasterPlan`
- or `C:\users\%USERNAME%\AppData\Local\MasterPlan` (on Windows)
- or `~/.local/share/MasterPlan` (on Linux)
- or `~/Library/Application Support/MasterPlan` (on Mac)
- or `./` (Legacy)

For: `masterplan-settings.json`:
- `XDG_CONFIG_HOME/MasterPlan`
- or `C:\users\%USERNAME%\AppData\Local\MasterPlan` (on Windows)
- or `~/.config/MasterPlan` (on Linux)
- or `~/Library/Preferences/MasterPlan` (on Mac)
- or `./` (Legacy)

Also, if settings file is not present at the new path, the program will try to read settings from old location (legacy `./`), allowing seamless transition for existing users.

2020-11-18 18:40 UTC, theogen-ratkin commented
Also changed `masterplan-settings.json` to `settings.json` since it's redundant to have program name 2 times in a path (`MasterPlan/masterplan-settings.json` -> `MasterPlan/settings.json`).

2020-11-22 03:22 UTC, SolarLune commented
Thanks for the PR - it does look pretty good, overall. 

I've made some suggestions; can you look over them?

2020-11-22 03:33 UTC, theogen-ratkin commented
@SolarLune Sure, but I can't see them. They should be over "Files changed" tab, right?

2020-11-22 03:50 UTC, SolarLune requested changes

2020-11-22 03:50 UTC, SolarLune commented on main.go
> +		logPath := filepath.FromSlash(xdg.DataHome + "/MasterPlan/log.txt")
Couldn't this just be `xdg.DataFile("MasterPlan/log.txt")`? Or am I missing something? That way, you wouldn't need to create the directory, as well, as `xdg` is supposed to do that.

2020-11-22 03:50 UTC, SolarLune commented on programSettings.go
> +	SETTINGS_FILENAME    = "settings.json"
Could you reduce these constants back to simply string definitions? It doesn't really make sense to define `SETTINGS_FILENAME` only to pass it once for `SETTINGS_PATH`.

2020-11-22 03:50 UTC, SolarLune commented on programSettings.go
> +	path := filepath.FromSlash(xdg.ConfigHome + SETTINGS_PATH)
Similarly to the previous request, do you need to use `xdg.ConfigHome` manually here? Seems like `xdg.ConfigFile()` could be used for this, right?

2020-11-22 03:51 UTC, SolarLune commented
Whoops, my mistake, I forgot to approve the requested changes (for whatever reason) - now they should be visible.

2020-11-22 04:40 UTC, theogen-ratkin commented
@SolarLune Done! Implemented all your suggestions. And indeed I should have used `DataFile` and `ConfigFile` from the start, they're just so convenient that I didn't even think they would exist, I'm so used to doing it myself. :smile:

2020-11-22 05:18 UTC, merged

2020-11-22 05:18 UTC, SolarLune commented
Haha, understandable.

Thanks for the changes, and thanks for the PR!